### ISSUE TITLE
KV7 Valmius käsitellä kaavasuosituksia

### ISSUE THREAD

**Issue by ltalve** [sitowise/Kauko#14]
Suunnittelija voi lisätä yleiskaavan aluevarausalueisiin nykytilakuvaukset ja niistä kullekin alueelle johdetut suunnitteluohjeet. Nykytilakuvaukset ja suunnitteluohjeet on kuvattu tekstinä.

Nykytilakuvaukset ja suunnitteluohjeet voivat olla kaavatietomallin mukaisia kaavasuosituksia, jotka liitetään kaavakohteisiin. Valmius käsitellä kaavasuosituksia tulee toteuttaa kaikkiin ohjelmistoihin.

**Comment by valttlapp** [comment]
Tietokanta tuki toteutettu tiketillä #7
