### ISSUE TITLE
KV9 Koko kaavaa koskevien määräysten/suositusten lisääminen ulkorajaan

### ISSUE THREAD

**Issue by ltalve** [sitowise/Kauko#16]
Suunnittelija voi lisätä kaavalle koko kaavaa koskevia yleisiä määräyksiä ja suosituksia.

Koko kaavaa koskevat määräykset ja suositukset liitetään tietomallin mukaisesti kaavan "ulkorajaan".

**Comment by valttlapp** [comment]
Tietokanta tuki toteutettu tiketillä #7
