### ISSUE TITLE
KV11 Mahdollisuus lisätä kaavaan liite (URL)

### ISSUE THREAD

**Issue by ltalve** [sitowise/Kauko#18]
Käyttäjä voi liittää asiakirjoja kaavan liitteeksi (esim. rakentamistapaohje) tietomallin mukaisesti.

Ohjelmistotoimittaja kuvaa ratkaisuehdotuksessa, miten toteutettaan: onko asiakirjaan vain viittaus vai tallennetaanko asiakirja järjestelmään.

Tässä vaiheessa toteutetaan URLina.

**Comment by valttlapp** [comment]
Tietokanta tuki toteutettu tiketillä #2
