### ISSUE TITLE
KV34 Asemakaavan topologisen eheyden varmistaminen

### ISSUE THREAD

**Issue by ltalve** [sitowise/Kauko#30]
Suunnittelijan on helppo tarkistaa noudattavatko kaavan korttelirajaukset kiinteistöjaotusta.

Ohjelmistokohtaista: Ratkaisuehdotuksessa kuvataan, miten tarkistus tapahtuu asemakaavan tuottamisen yhteydessä. Aina ei kuitenkaan ole mahdollista noudattaa kiinteistörajoja, joten ei voi pakottaa. Vertailussa voidaan käyttää MML tai kunnan kiinteistörajaaineistoa.

**Comment by SannaJokela** [comment]
Tämä varmaan onnistuu ihan QGISin topologia-asetuksilla. Eli onko tästä ohjeistusta?

**Comment by SannaJokela** [comment]
Ohjeistukssa olikin: Topologiatarkastuksilla varmistetaan, että kaava-aineisto on eheää eivätkä luodut kaavakohteet
muodosta virheellisiä geometriasuhteita toisiinsa. Kauko tekee automaattisesti tarvittavat
topologiatarkastukset. Tarkastukset kattavat seuraavat kaavakohteet:
• kaavan ulkoraja suhteessa maankäyttöalueisiin (maankäyttöalueiden tulee sijaita
kaavan sisällä)
• maankäyttöalueet suhteessa toisiinsa
• Voimassa olevat kaavarajat eivät leikkaa toisiaan
• Kaava kohteet ovat maakäyttöalueiden sisällä
